<?php
require_once "../Admin/Helpers/config_helper.php";
require_once "../Admin/Helpers/validation_helper.php";
require_once "../helper.php";
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <?php require_once('css.php'); ?>
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <div style="background-color: #F2F6FD;">
        	<?php require_once('menu.php'); ?>
        </div>
        <!-- Header End -->
        <div class="container-fluid py-4 page-header mb-5 menupolicy">
        	<h3 class="text-white animated slideInDown">Terms & Conditions</h3>
        </div>
        <div class="container-fluid pb-4">
            <div class="row align-items-center">
                <h5>1.USAGE OF TANKHWAA</h5>
                <p><i class="fa fa-check text-primary me-3"></i>The Tankhwaa platform (website) is provided by Tankhwaa Incorporation Through the Tankhwaa Platform any person with a verified account post jobs (“Job Poster”) to the Tankhwaa Platform, access and participate in the services provided by Tankhwaa. By using Tankhwaa Platform, you consent to the terms of the Terms of Service in addition to our Privacy Policy.</p>
                <p><i class="fa fa-check text-primary me-3"></i>A Job Poster accessing the Tankhwaa Platform shall be bound by these Terms of Service, and all other rules, regulations and terms of use referred to herein or provided by Tankhwaa in relation to any services provided via the Tankhwaa Platform.</p>
                
                <p><i class="fa fa-check text-primary me-3"></i>Tankhwaa shall be entitled to modify these Terms of Service, rules, regulations and terms of use referred to herein or provided by Tankhwaa in relation to any Tankhwaa Services, at any time, by posting the same on the Tankhwaa Platform. Use of Tankhwaa constitutes the Job Poster's acceptance of such modified Terms of Service, rules, regulations and terms of use referred to herein or provided by Tankhwaa in relation to any Tankhwaa Services, as may be amended from time to time. Tankhwaa may, at its sole discretion, also notify the Job Poster of any change or modification in these Terms of Service, rules, regulations and terms of use referred to herein or provided by Tankhwaa, by way of sending an email to the Job Poster's registered email address or posting notifications in the Job Poster accounts. The Job Poster may then exercise the options provided in such an email or notification to indicate non-acceptance of the modified Terms of Service, rules, regulations and terms of use referred to herein or provided by Tankhwaa. If such options are not exercised by the Job Poster within the time frame prescribed in the email or notification, the Job Poster will be deemed to have accepted the modified Terms of Service, rules, regulations and terms of use referred to herein or provided by Tankhwaa.</p>
                <p><i class="fa fa-check text-primary me-3"></i>Certain Tankhwaa Services being provided on Tankhwaa may be subject to additional rules and regulations set down in that respect. To the extent that these Terms of Service are inconsistent with the additional conditions set down, the additional conditions shall prevail. Tankhwaa may, at its sole and absolute discretion:</p>
                <p><i class="fa fa-check text-primary me-3"></i>Restrict, suspend, or terminate any Job Poster's access to all or any part of the Tankhwaa Platform or Tankhwaa Services; Change, suspend, or discontinue all or any part of the Tankhwaa Platform or Tankhwaa Services; Reject, move, or remove any material that may be submitted by a Job Poster;
Move or remove any content that is available on the Tankhwaa Platform;
Deactivate or delete a Job Poster's account and all related information and files on the account;
Establish general practices and limits concerning use of Tankhwaa Platform;
Assign its rights and liabilities to all Job Poster accounts hereunder to any entity (post such assignment intimation of such assignment shall be sent to all Job Posters to their registered email ids).
In the event any Job Poster breaches, or Tankhwaa reasonably believes that such Job Poster has breached these Terms of Service, or has illegally or improperly used the Tankhwaa Platform or Tankhwaa Services, Tankhwaa may, at its sole and absolute discretion, and without any notice to the Job Poster, restrict, suspend or terminate such Job Poster's access to all or any part of the Tankhwaa Platform, deactivate or delete the Job Poster's account and all related information on the account, delete any content posted by the Job Poster on Tankhwaa and further, take technical and legal steps as it deems necessary.
If Tankhwaa charges its Job Posters a platform fee in respect of any Tankhwaa Services, Tankhwaa shall, without delay, repay such platform fee in the event of suspension or removal of the Job Poster's account or Tankhwaa Services on account of any negligence or deficiency on the part of Tankhwaa, but not if such suspension or removal is affected due to:
any breach or inadequate performance by the Job Poster of any of these Terms of Service; or
any circumstances beyond the reasonable control of Tankhwaa.
By accepting these Terms of Service Job Posters are providing their consent to receiving communications such as announcements, administrative messages and advertisements from Tankhwaa or any of its partners, licensors or associates.</p>
				<h5>2.PARTICIPATION</h5>
                <p><i class="fa fa-check text-primary me-3"></i>When accessing and interacting with the Tankhwaa Platform and Tankhwaa Services a Job Poster will be able to post jobs to source and hire potential candidates and employees for the Job Poster's organisation, view the profiles of suitable candidates who have the requisite skills and experience for the particular job(s) that the Job Poster is hiring for and schedule interviews with potential candidates/employees.</p>
<p><i class="fa fa-check text-primary me-3"></i>To post a job a Job Poster shall be required to provide information about the job such as the job role, whether the job is part-time or full time, the days of work, work timings, the salary range for the job, the number of openings for the said job the minimum education level and the level of experience required for the job. While Tankhwaa does not tolerate or allow for discrimination on the basis of gender, Tankhwaa also recognizes that certain jobs might be gender specific and Job Posters have the option of specifying whether a job is gender specific. By agreeing to these Terms of Service and while posting a job on the Tankhwaa Platform, Job Posters undertake that all information posted about a job will at all times be accurate, not be misleading that the Job Poster is not indulging in any discriminatory practices. The Job Poster understands and acknowledges that any incorrect information or misrepresentations about a job will affect the efficacy of the Tankhwaa Platform and Tankhwaa Services and that Tankhwaa shall have the right to remove a job posting or suspend the Job Poster’s account.</p>
<p><i class="fa fa-check text-primary me-3"></i>The job applications by the candidates on the Tankhwaa Platform shall remain active only for a period of 60 (sixty) days from the date of application to the job posts and upon the expiry of the said period of 60 (sixty) days, such job applications shall be archived.
Job Posters agree that they shall at all times be bound by and adhere to the Code of Conduct while posting jobs through the Tankhwaa Platform and while using the Tankhwaa Services.</p>
				<h5>3.INTELLECTUAL PROPERTY</h5>
                <p><i class="fa fa-check text-primary me-3"></i>The intellectual property rights (“Intellectual Property Rights”) in all software underlying the Tankhwaa Platform and the Tankhwaa Services and material published on the Tankhwaa Platform, including (but not limited to) software, advertisements, content (whether written, audio and/or visual), photographs, graphics, images, illustrations, graphs, charts, marks, logos, audio or video clippings, animations etc. is owned by Tankhwaa, its affiliates, partners, licensors and/or associates. Users may not modify, publish, transmit, participate in the transfer or sale of, reproduce, create derivative works of, distribute, publicly perform, publicly display, or in any way exploit any of the materials or content on Tankhwaa either in whole or in part without express written licence from Tankhwaa.</p>
<p><i class="fa fa-check text-primary me-3"></i>Users are solely responsible for all materials (whether publicly posted or privately transmitted) that they upload, post, e-mail, transmit, or otherwise make available via the Tankhwaa Platform (“Users' Content”). Each User represents and warrants that they own all Intellectual Property Rights in the Users' Content and that no part of the User's Content infringes any third-party rights. Users further confirm and undertake to not display or use of the names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights of any third party on the Tankhwaa Platform, without written authorization from such third party. Users agree to indemnify and hold harmless Tankhwaa, its directors, employees, affiliates and assigns against all costs, damages, loss and harm including towards litigation costs and counsel fees, in respect of any third party claims that may be initiated including for infringement of Intellectual Property Rights arising out of such display or use of the names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on the Tankhwaa Platform, by such User or through the User's commissions or omissions
Users hereby grant to Tankhwaa and its affiliates, partners, licensors and associates a worldwide, irrevocable, royalty-free, non-exclusive, sub-licensable licence to use, reproduce, create derivative works of, distribute, publicly perform, publicly display, transfer, transmit, and/or publish Users' Content for any of the following purposes:
displaying Users' Content on Tankhwaa
distributing Users' Content, either electronically or via other media, to potential candidates, and/or
storing Users' Content in a remote database accessible by end users, for a charge.
This licence shall apply to the distribution and the storage of Users' Content in any form, medium, or technology.
All names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on the Tankhwaa Platform belonging to any person (including a User), entity or third party are recognized as proprietary to the respective owners and any claims, controversy or issues against these names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights must be directly addressed to the respective parties under notice to Tankhwaa.</p>
					<h5>4.Third Party Sites, Services and Products</h5>
                   <p><i class="fa fa-check text-primary me-3"></i>Links to other Internet sites or mobile applications owned and operated by third parties may be provided via the Tankhwaa Platform. Users' use of each of those sites is subject to the conditions, if any, posted by those sites. Tankhwaa does not exercise control over any Internet sites or mobile applications apart from the Tankhwaa Platform and cannot be held responsible for any content residing in any third-party Internet site or mobile application. Tankhwaa's inclusion of third-party content or links to third-party Internet sites or mobile applications is not an endorsement by Tankhwaa of such third-party Internet sites or mobile applications.</p>
                   <p><i class="fa fa-check text-primary me-3"></i>Users' correspondence, transactions/offers or related activities with third parties including but not limited to potential candidates, payment providers and verification service providers, are solely between the User and that third party. Users' correspondence, transactions and usage of the services/offers of such third party shall be subject to the terms and conditions, policies and other service terms adopted/implemented by such third party, and the User shall be solely responsible for reviewing the same prior to transacting or availing of the services/offers of such third party. The User agrees that Tankhwaa will not be responsible or liable for any loss or damage of any sort incurred as a result of any such transactions/offers with third parties. Any questions, complaints, or claims related to any third-party product or service should be directed to the appropriate vendor.</p>
					<p><i class="fa fa-check text-primary me-3"></i>The Tankhwaa Platform contains content that is created by Tankhwaa as well as content provided by third parties (including potential candidates). Tankhwaa does not guarantee the accuracy, integrity, quality of the content provided by third parties and such content may not be relied upon by the Users in utilising the Tankhwaa Services provided on the Tankhwaa Platform.</p>
                    <h5>5.PARTICIPATION</h5>
                    <p><i class="fa fa-check text-primary me-3"></i>All information collected from Users, such as registration (including but not limited to email addresses, mobile phone numbers, government identity documentation) and payment information, is subject to Tankhwaa's Privacy Policy which is available atPrivacy Policy.</p>
<p><i class="fa fa-check text-primary me-3"></i>We do not share personal information of any individual with other companies/entities without obtaining permission. We may share all such information that we have in our possession in accordance with our Privacy Policy.</p>
<p><i class="fa fa-check text-primary me-3"></i>Once the personal information has been shared with you, you shall, at all times, be responsible to secure such information.</p>
<p><i class="fa fa-check text-primary me-3"></i>You warrant and represent that you shall not disclose or transfer personal information shared by us to any sub-processors without ensuring adequate and equivalent safeguards to the personal information.</p>
<p><i class="fa fa-check text-primary me-3"></i>You, hereby agree and acknowledge that you will use the information shared with you only for the purpose of the Services. You shall not use such information for any personal or other business purposes. In the event you are found to be misusing the information shared with you, we shall, at our sole discretion, delete your account with immediate effect and you will be blocked from using/ accessing Tankhwaa Platform in future.</p>
					<h5>6.Eligibility</h5>
                    <p><i class="fa fa-check text-primary me-3"></i>The Tankhwaa Platform is open only to persons above the age of 18 years.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>The Tankhwaa Platform is open only to persons currently residing in India.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Persons who wish to participate must have a valid email address and/or mobile phone number.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Tankhwaa may on receipt of information bar a person from accessing their Tankhwaa account if such person is found to be in violation of any part of these Terms of Service or the Code of Conduct. Only those Users who have successfully registered on the Tankhwaa Platform shall be eligible to Post Jobs.</p>
                    
                    <h5>7.Job Posters Conduct</h5>
                      <p><i class="fa fa-check text-primary me-3"></i>Job Posters agree to abide by these Terms of Service and all other rules, regulations and terms of use of the Website. In the event Job Poster does not abide by these Terms of Service and all other rules, regulations and terms of use, Tankhwaa may, at its sole and absolute discretion, take necessary remedial action, including but not limited to:
                        restricting, suspending, or terminating any Job Poster's access to all or any part of Tankhwaa Services;
                        deactivating or deleting a Job Poster's account and all related information and files on the account. Any amount remaining unused in the Job Poster's account on the date of deactivation or deletion shall be transferred to the Job Poster's bank account on record with Tankhwaa subject to a processing fee (if any) applicable on such transfers as set out herein.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Job Posters agree to provide true, accurate, current and complete information at the time of registration and at all other times (as required by Tankhwaa). Job Posters further agree to update and keep updated their registration information and information related to job posts made on the Tankhwaa Platform.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>A Job Poster shall not register or operate more than one Job Poster account with Tankhwaa.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Job Posters agree to ensure that they can receive all communication from Tankhwaa by marking emails or sending SMSs from Tankhwaa. Tankhwaa shall not be held liable if any email/SMS remains unread by a Job Poster as a result of such e-mail getting delivered to the Job Poster's junk or spam folder.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Any password issued by Tankhwaa to a Job Poster may not be revealed to anyone else. Job Posters may not use anyone else's password. Job Posters are responsible for maintaining the confidentiality of their accounts and passwords. Job Posters agree to immediately notify Tankhwaa of any unauthorised use of their passwords or accounts or any other breach of security.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Job Posters agree to exit/log-out of their accounts at the end of each session. Tankhwaa shall not be responsible for any loss or damage that may result if the Job Poster fails to comply with these requirements.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Job Posters agree not to use cheats, exploits, automation, software, bots, hacks or any unauthorised third-party software designed to modify or interfere with the Tankhwaa Services and/or Tankhwaa experience or assist in such activity.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Job Posters agree not to copy, modify, rent, lease, loan, sell, assign, distribute, reverse engineer, grant a security interest in, or otherwise transfer any right to the technology or software underlying Tankhwaa or Tankhwaa’s Services.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Job Posters agree that without Tankhwaa's express written consent, they shall not modify or cause to be modified any files or software that are part of Tankhwaa's Services or the Tankhwaa Platform.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Job Posters agree not to disrupt, overburden, or aid or assist in the disruption or overburdening of (a) any computer or server used to offer or support Tankhwaa or the Tankhwaa’s Services (each a "Server"); or (2) the enjoyment of Tankhwaa Services by any other Job Poster or person.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Job Posters agree not to institute, assist or become involved in any type of attack, including without limitation to distribution of a virus, denial of service, or other attempts to disrupt Tankhwaa Services or any other person's use or enjoyment of Tankhwaa Services.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Job Posters shall not attempt to gain unauthorised access to Job Poster accounts, Servers or networks connected to Tankhwaa Services by any means other than the Job Poster interface provided by Tankhwaa, including but not limited to, by circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person to circumvent or modify, any security, technology, device, or software that underlies or is part of Tankhwaa Services.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>A Job Poster shall not publish any content that is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person.</p>
                        <b>Without limiting the foregoing, Job Posters agree not to use Tankhwaa for any of the following:</b>
                        <p><i class="fa fa-check text-primary me-3"></i>To engage in any obscene, offensive, indecent, racial, communal, anti-national, objectionable, defamatory or abusive action or communication;</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To harass, stalk, threaten, or otherwise violate any legal rights of other individuals;</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To publish, post, upload, e-mail, distribute, or disseminate (collectively, "Transmit") any inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful content;</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To Transmit files that contain viruses, corrupted files, or any other similar software or programs that may damage or adversely affect the operation of another person's computer, Tankhwaa, any software, hardware, or telecommunications equipment;</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To advertise, offer or sell any goods or services for any commercial purpose on Tankhwaa including but not limited to multi-level marketing for a third party, promoting business of a third party, selling financial products such as loans, insurance, promoting demat account openings, without the express written consent of Tankhwaa;</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To download any file, recompile or disassemble or otherwise affect our products that you know or reasonably should know cannot be legally obtained in such manner;</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or the source of software or other material;</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To restrict or inhibit any other Job Poster from using and enjoying any public area within our sites;
                        To collect or store personal information about other Job Posters;</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To collect or store information about potential candidates;</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To mine information relating to potential candidates with the aim of creating a database of potential candidates whether or not such database is used or meant to be used by the Job Poster or any third party associated with the Job Poster or to whom such Job Poster makes such mined information available, for either a commercial purpose of for the Job Poster's own use at a future date;</p>
                        
                        <p><i class="fa fa-check text-primary me-3"></i>To interfere with or disrupt the Tankhwaa and/or the Tankhwaa Platform, Tankhwaa servers, or Tankhwaa networks;</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To impersonate any person or entity, including, but not limited to, a representative of Tankhwaa, or falsely state or otherwise misrepresent Job Poster's affiliation with a person or entity;</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To forge headers or manipulate identifiers or other data in order to disguise the origin of any content transmitted through Tankhwaa or to manipulate Job Poster's presence on the Tankhwaa Platform;</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To take any action that imposes an unreasonably or disproportionately large load on Tankhwaa’s infrastructure;
                        To engage in any illegal activities.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>To engage in any action that threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting other nation.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>If a Job Poster chooses a username that, in Tankhwaa's considered opinion is obscene, indecent, abusive or that might subject Tankhwaa to public disparagement or scorn, or a name which is an official team/league/franchise names and/or name of any sporting personality, as the case may be, Tankhwaa reserves the right, without prior notice to the Job Poster, to restrict usage of such names, which in Tankhwaa’s opinion fall within any of the said categories and/or change such username and intimate the Job Poster or delete such username and posts from Tankhwaa, deny such Job Poster access to Tankhwaa, or any combination of these options.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Unauthorised access to the Tankhwaa Platform is a breach of these Terms of Service, and a violation of the law. Job Posters agree not to access the Tankhwaa Platform by any means other than through the interface that is provided by Tankhwaa via the Tankhwaa Platform for use in accessing the Tankhwaa Platform. Job Posters agree not to use any automated means, including, without limitation, agents, robots, scripts, or spiders, to access, monitor, or copy any part of the Tankhwaa Platform, Tankhwaa Services or any information available for access through the Tankhwaa Platform or Tankhwaa Services, except those automated means that Tankhwaa has approved in advance and in writing.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Use of the Tankhwaa Platform is subject to existing laws and legal processes. Nothing contained in these Terms of Service shall limit Tankhwaa's right to comply with governmental, court, and law-enforcement requests or requirements relating to Job Posters' use of Tankhwaa.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Persons below the age of eighteen (18) years are not allowed to register with the Tankhwaa Platform. All persons interested in becoming Tankhwaa Job Posters might be required by Tankhwaa to disclose their age at the time of getting access to the Tankhwaa Platform. If a person declares a false age, Tankhwaa shall not be held responsible and such person shall, in addition to forfeiting any and all rights over their Tankhwaa account, shall indemnify and hold Tankhwaa, its Directors, officers, employees, agents, affiliates harmless of any and all losses that may be suffered by Tankhwaa its Directors, officers, employees, agents, affiliates by virtue of such false declaration being made. In case the person making the false declaration is below the age of 18 such person's legal guardians shall indemnify and hold Tankhwaa, its Directors, officers, employees, agents, affiliates harmless of any and all losses that may be suffered by Tankhwaa its Directors, officers, employees, agents, affiliates by virtue of such false declaration having been made by said person.</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Tankhwaa may not be held responsible for any content contributed by Job Posters on the Tankhwaa Platform. </p>
                                            
                   <h5>8.Dispute and Dispute Resolution</h5>
                                            <p><i class="fa fa-check text-primary me-3"></i>If any dispute arising out of, or in connection with, the Tankhwaa Services provided by Tankhwaa via the Tankhwaa Platform, the construction, validity, interpretation and enforceability of these Terms of Service, or the rights and obligations of the Job Poster(s) or Tankhwaa, as well as the exclusive jurisdiction to grant interim or preliminary relief in case of any dispute referred to arbitration as given below arises between the Job Poster(s) and Tankhwaa ("Dispute"), the disputing parties hereto shall endeavour to settle such Dispute amicably. The attempt to bring about an amicable settlement shall be considered to have failed if not resolved within 30 (thirty) days from the date of communicating the Dispute in writing.</p>
                    
                    <h5>9.Limitations of Liability</h5>
                    <p><i class="fa fa-check text-primary me-3"></i>ob Posters shall access the Tankhwaa Services provided via the Tankhwaa Platform voluntarily and at their own risk. Tankhwaa shall, under no circumstances be held responsible or liable on account of any loss or damage sustained by Job Posters or any other person or entity during the course of access to the Tankhwaa Platform.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>By accessing the Tankhwaa Platform and Tankhwaa Services provided therein, Job Posters hereby release from and agree to indemnify Tankhwaa, and/or any of its directors, employees, partners, associates and licensors, from and against all liability, cost, loss or expense arising out their access of the Tankhwaa Platform and the Tankhwaa Services including (but not limited to) personal injury and damage to property and whether direct, indirect, consequential, foreseeable, due to some negligent act or omission on their part, or otherwise.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Tankhwaa accepts no liability, whether jointly or severally, for any errors or omissions, whether on behalf of itself or third parties in relation to the data/information collated and published on the Tankhwaa Platform.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Job Posters shall be solely responsible for any consequences which may arise due to their access of Tankhwaa Services by conducting an illegal act or due to non-conformity with these Terms of Service and other rules and regulations in relation to Tankhwaa Services, including provision of incorrect personal details. Job Posters also undertake to indemnify Tankhwaa and their respective officers, directors, employees and agents on the happening of such an event (including without limitation cost of attorney, legal charges etc.) on full indemnity basis for any loss/damage suffered by Tankhwaa on account of such act on the part of the Job Posters.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Job Posters shall indemnify, defend, and hold Tankhwaa harmless from any third party/entity/organisation claims arising from or related to such Job Poster's engagement with the Tankhwaa Platform. In no event shall Tankhwaa be liable to any Job Poster for acts or omissions arising out of or related to Job Poster's engagement with the Tankhwaa Platform.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>In consideration of Tankhwaa allowing Job Posters to access the Tankhwaa Platform, to the maximum extent permitted by law, the Job Posters waive and release each and every right or claim, all actions, causes of actions (present or future) each of them has or may have against Tankhwaa, its respective agents, directors, officers, business associates, group companies, sponsors, employees, or representatives for all and any injuries, accidents, or mishaps (whether known or unknown) or (whether anticipated or unanticipated) arising out of the provision of Tankhwaa Services.</p>

					<h5>10.Disclaimers</h5>
                    <p><i class="fa fa-check text-primary me-3"></i>To the extent permitted under law, neither Tankhwaa nor its parent/holding company, subsidiaries, affiliates, directors, officers, professional advisors, employees shall be responsible for the deletion, the failure to store, the mis-delivery, or the untimely delivery of any information or material.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>To the extent permitted under law, Tankhwaa shall not be responsible for any harm resulting from downloading or<p><i class="fa fa-check text-primary me-3"></i> accessing any information or material, the quality of servers, products, Tankhwaa Services or sites.</p>
                    Any material accessed, downloaded or otherwise obtained through the Tankhwaa Platform is done at the Job Poster's discretion, competence, acceptance and risk, and the Job Poster will be solely responsible for any potential damage to Job Poster's computer system or loss of data that results from a Job Poster's download of any such material.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Tankhwaa shall make best endeavours to ensure that the Tankhwaa(s) is error-free and secure, however, neither Tankhwaa nor any of its partners, licensors or associates makes any warranty that:
                    the Tankhwaa Platform will meet Job Posters' requirements,
                    Tankhwaa Platform will be uninterrupted, timely, secure, or error free
                    the results that may be obtained from the use of Tankhwaa Platform will be accurate or reliable; and
                    the quality of any products, Tankhwaa Services, information, or other material that Job Posters purchase or obtain through the Tankhwaa Platform will meet Job Posters' expectations.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>In case Tankhwaa discovers any error, Tankhwaa reserves the right (exercisable at its discretion) to rectify the error in such manner as it deems fit, including through a set-off of the erroneous payment from amounts due to the Job Poster or deduction from the Job Poster's account of the amount of erroneous payment. In case of exercise of remedies in accordance with this clause, Tankhwaa agrees to notify the Job Poster of the error and of the exercise of the remedy(ies) to rectify the same.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>To the extent permitted under law, neither Tankhwaa nor its partners, licensors or associates shall be liable for any direct, indirect, incidental, special, or consequential damages arising out of the use of or inability to use our sites, even if we have been advised of the possibility of such damages.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Any Tankhwaa Services being hosted or provided, or intended to be hosted on the Tankhwaa platform and requiring specific permission or authority from any statutory authority or any state or the central government, or the board of directors shall be deemed cancelled or terminated, if such permission or authority is either not obtained or denied either before or after the availability of the relevant Tankhwaa Services are hosted or provided.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>To the extent permitted under law, in the event of suspension or closure of any Tankhwaa Services Job Posters shall not be entitled to make any demands, claims, on any nature whatsoever.</p>
             </div> 
        </div>
        <?php require_once('footer.php'); ?>
	</div>
    <?php require_once('js.php'); ?>
</body>

</html>